apps/urls.py
from django.conf.urls import url

from . import views

app_name = "apps"
urlpatterns = [
    url(r'^$', views.home, name='recipe'),
    url(r'^create_category/$', views.create_category, name='create_category'),
    url(r'^save_category/$', views.save_category, name='save_category'),
    url(r'^(?P<recipe_id>[0-9]+)/details/$', views.details, name='details'),
    url(r'^(?P<recipe_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^add_image/(?P<id>\d+)', views.AddImage, name="addimage"),

]

image/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^recipe/', include("apps.urls")),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Image(models.Model):
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.image

apps/forms.py
from django.forms import ModelForm
from .models import *


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

apps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category
from .forms import *


def home(request):
    students = Category.objects.all()
    return render(request, "home.html", {"students": students})


def create_category(request):
    recipe_form = CategoryForm()
    return render(request, "create_category.html", {"form": recipe_form})


def save_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/recipe/')
        else:
            return render(request, 'create_category.html', {"form": form})

    else:
        form = CategoryForm()
        return render(request, 'create_category.html', {"form": form})


def AddImage(request, id):
    if request.method == 'POST':
        id = request.POST['id']
        category = Category.objects.get(id=id)
        image = Image(image=request.POST['img'], category=category)
        image.save()
        image = category.image_set.all()
        return render(request, 'add_image.html', {'categorys': category, 'images': image})
    else:
        category = Category.objects.get(id=id)
        image = category.image_set.all()
        return render(request, 'add_image.html', {'categorys': category, 'images': image})


def details(request, recipe_id):
    students = Category.objects.get(id=recipe_id)
    return render(request, "details.html", {"student": students})


def delete(request, recipe_id):
    Category.objects.get(id=recipe_id).delete()
    return HttpResponseRedirect('/recipe/')

apps/templates/add_image.html
<div class="container">


  <form action="{% url 'addimage' id=0%}" method="post">{% csrf_token %}
    <div class="form-group">
      <label for="usr">Add image:</label>
      <img src="/media/{{anil.jpg}}" alt="jai hind" width="500" height="600" name="img">
        <input type="hidden" class="form-control" id="usr" name="id" value="{{categorys.id}}">
    </div><br><br>
    <button type="submit" class="btn btn-default">Submit</button><br><br>
  </form>
    <table class="table">
    <thead>
      <tr>
        <th>image list</th>
      </tr>
    </thead>
    <tbody>
     {% for img in images %}
      <tr>
        <td><img src="/media/{{each.image}}"> alt="jai hind" width="500" height="600" name="img"></td>


      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

apps/templates/create_category.html
{% if error %}
<b>{{error}}</b><br>
<h1>hi</h1>
{% endif %}
<form action="{% url 'apps:save_category' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>

apps/templates/details.html
Image: <img src="/media/{{student.image}}"><br>

{% if error %}
<b>{{error}}</b><br>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save Image">
</form>
<a href="/recipe/">Back</a>

apps/templates/home.html
<h1> Categories</h1>
{% if students%}
    {% for each in students %}
        <a href="{% url 'apps:details' each.id %}">{{each.name}}</a><a href="{% url 'apps:delete' each.id %}"> delete</a><br>
    {% endfor %}

{% else %}
 Please Create Category
{% endif %}
<br>

<a href="/create_category/">Create Category</a>